<a href="https://colab.research.google.com/github/Fa-Abdullah/Appie-Responsive-Website/blob/main/Tolerant_Information_Retrieval_System_using_Inverted_Index_and_Web_Scraping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Web Scraping

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

In [ ]:
base_url = "https://books.toscrape.com/catalogue/page-{}.html"

books_data = []
book_id = 1

num_pages = 50

In [ ]:
for page in range(1, num_pages + 1):

    url = base_url.format(page)
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    for book in books:
        relative_link = book.h3.a["href"]

        book_url = (
            "https://books.toscrape.com/catalogue/"
            + relative_link.replace("../../../", "")
        )

        book_response = requests.get(book_url)
        book_soup = BeautifulSoup(book_response.text, "html.parser")

        title = book_soup.find("div", class_="product_main").h1.text.strip()

        breadcrumb = book_soup.find("ul", class_="breadcrumb").find_all("li")
        category = breadcrumb[2].text.strip()

        description_tag = book_soup.find("div", id="product_description")

        if description_tag:
            description = description_tag.find_next_sibling("p").text.strip()
        else:
            description = ""

        books_data.append([
            book_id,
            title,
            category,
            description
        ])

        print(f"{book_id} - {title}")

        book_id += 1
        time.sleep(0.2)

1 - A Light in the Attic
2 - Tipping the Velvet
3 - Soumission
4 - Sharp Objects
5 - Sapiens: A Brief History of Humankind
6 - The Requiem Red
7 - The Dirty Little Secrets of Getting Your Dream Job
8 - The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
9 - The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
10 - The Black Maria
11 - Starving Hearts (Triangular Trade Trilogy, #1)
12 - Shakespeare's Sonnets
13 - Set Me Free
14 - Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
15 - Rip it Up and Start Again
16 - Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
17 - Olio
18 - Mesaerion: The Best Science Fiction Stories 1800-1849
19 - Libertarianism for Beginners
20 - It's Only the Himalayas
21 - In Her Wake
22 - How Music Works
23 - Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More
24 - Chase Me (Paris Nights #2)
25 - Black Dust
26 - Birdsong: A Story in Pictures
27 - America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana
28 - Aladdin and His Wonderful Lamp
29 - Worlds Elsewhere: Journeys Around Shakespeareâs Globe
30 - Wall and Piece
31 - The Four Agreements: A Practical Guide to Personal Freedom
32 - The Five Love Languages: How to Express Heartfelt Commitment to Your Mate
33 - The Elephant Tree
34 - The Bear and the Piano
35 - Sophie's World
36 - Penny Maybe
37 - Maude (1883-1993):She Grew Up with the country
38 - In a Dark, Dark Wood
39 - Behind Closed Doors
40 - You can't bury them all: Poems
41 - Slow States of Collapse: Poems
42 - Reasons to Stay Alive
43 - Private Paris (Private #10)
44 - #HigherSelfie: Wake Up Your Life. Free Your Soul. Find Your Tribe.
45 - Without Borders (Wanderlove #1)
46 - When We Collided
47 - We Love You, Charlie Freeman
48 - Untitled Collection: Sabbath Poems 2014
49 - Unseen City: The Majesty of Pigeons, the Discreet Charm of Snails & Other Wonders of the Urban Wilderness
50 - Unicorn Tracks
51 - Unbound: How Eight Technologies Made Us Human, Transformed Society, and Brought Our World to the Brink
52 - Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRoNiCLE #2)
53 - Throwing Rocks at the Google Bus: How Growth Became the Enemy of Prosperity
54 - This One Summer
55 - Thirst
56 - The Torch Is Passed: A Harding Family Story
57 - The Secret of Dreadwillow Carse
58 - The Pioneer Woman Cooks: Dinnertime: Comfort Classics, Freezer Food, 16-Minute Meals, and Other Delicious Ways to Solve Supper!
59 - The Past Never Ends
60 - The Natural History of Us (The Fine Art of Pretending #2)
61 - The Nameless City (The Nameless City #1)
62 - The Murder That Never Was (Forensic Instincts #5)
63 - The Most Perfect Thing: Inside (and Outside) a Bird's Egg
64 - The Mindfulness and Acceptance Workbook for Anxiety: A Guide to Breaking Free from Anxiety, Phobias, and Worry Using Acceptance and Commitment Therapy
65 - The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing
66 - The Inefficiency Assassin: Time Management Tactics for Working Smarter, Not Longer
67 - The Gutsy Girl: Escapades for Your Life of Epic Adventure
68 - The Electric Pencil: Drawings from Inside State Hospital No. 3
69 - The Death of Humanity: and the Case for Life
70 - The Bulletproof Diet: Lose up to a Pound a Day, Reclaim Energy and Focus, Upgrade Your Life
71 - The Art Forger
72 - The Age of Genius: The Seventeenth Century and the Birth of the Modern Mind
73 - The Activist's Tao Te Ching: Ancient Advice for a Modern Revolution
74 - Spark Joy: An Illustrated Master Class on the Art of Organizing and Tidying Up
75 - Soul Reader
76 - Security
77 - Saga, Volume 6 (Saga (Collected Editions) #6)
78 - Saga, Volume 5 (Saga (Collected Editions) #5)
79 - Reskilling America: Learning to Labor in the Twenty-First Century
80 - Rat Queens, Vol. 3: Demons (Rat Queens (Collected Editions) #11-15)
81 - Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1)
82 - Princess Between Worlds (Wide-Awake Princess #5)
83 - Pop Gun War, Volume 1: Gift
84 - Political Suicide: Missteps, Peccadilloes, Bad Calls, Backroom Hijinx, Sordid Pasts, Rotten Breaks, and Just Plain Dumb Mistakes in the Annals of American Politics
85 - Patience
86 - Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1)
87 - orange: The Complete Collection 1 (orange: The Complete Collection #1)
88 - Online Marketing for Busy Authors: A Step-By-Step Guide
89 - On a Midnight Clear
90 - Obsidian (Lux #1)
91 - My Paris Kitchen: Recipes and Stories
92 - Masks and Shadows
93 - Mama Tried: Traditional Italian Cooking for the Screwed, Crude, Vegan, and Tattooed
94 - Lumberjanes, Vol. 2: Friendship to the Max (Lumberjanes #5-8)
95 - Lumberjanes, Vol. 1: Beware the Kitten Holy (Lumberjanes #1-4)
96 - Lumberjanes Vol. 3: A Terrible Plan (Lumberjanes #9-12)
97 - Layered: Baking, Building, and Styling Spectacular Cakes
98 - Judo: Seven Steps to Black Belt (an Introductory Guide for Beginners)
99 - Join
100 - In the Country We Love: My Family Divided
101 - Immunity: How Elie Metchnikoff Changed the Course of Modern Medicine
102 - I Hate Fairyland, Vol. 1: Madly Ever After (I Hate Fairyland (Compilations) #1-5)
103 - I am a Hero Omnibus Volume 1
104 - How to Be Miserable: 40 Strategies You Already Use
105 - Her Backup Boyfriend (The Sorensen Family #1)
106 - Giant Days, Vol. 2 (Giant Days #5-8)
107 - Forever and Forever: The Courtship of Henry Longfellow and Fanny Appleton
108 - First and First (Five Boroughs #3)
109 - Fifty Shades Darker (Fifty Shades #2)
110 - Everydata: The Misinformation Hidden in the Little Data You Consume Every Day
111 - Don't Be a Jerk: And Other Practical Advice from Dogen, Japan's Greatest Zen Master
112 - Danganronpa Volume 1
113 - Crown of Midnight (Throne of Glass #2)
114 - Codename Baboushka, Volume 1: The Conclave of Death
115 - Camp Midnight
116 - Call the Nurse: True Stories of a Country Nurse on a Scottish Isle
117 - Burning
118 - Bossypants
119 - Bitch Planet, Vol. 1: Extraordinary Machine (Bitch Planet (Collected Editions))
120 - Avatar: The Last Airbender: Smoke and Shadow, Part 3 (Smoke and Shadow #3)
121 - Algorithms to Live By: The Computer Science of Human Decisions
122 - A World of Flavor: Your Gluten Free Passport
123 - A Piece of Sky, a Grain of Rice: A Memoir in Four Meditations
124 - A Murder in Time
125 - A Flight of Arrows (The Pathfinders #2)
126 - A Fierce and Subtle Poison
127 - A Court of Thorns and Roses (A Court of Thorns and Roses #1)
128 - (Un)Qualified: How God Uses Broken People to Do Big Things
129 - You Are What You Love: The Spiritual Power of Habit
130 - William Shakespeare's Star Wars: Verily, A New Hope (William Shakespeare's Star Wars #4)
131 - Tuesday Nights in 1980
132 - Tracing Numbers on a Train
133 - Throne of Glass (Throne of Glass #1)
134 - Thomas Jefferson and the Tripoli Pirates: The Forgotten War That Changed American History
135 - Thirteen Reasons Why
136 - The White Cat and the Monk: A Retelling of the Poem âPangur BÃ¡nâ
137 - The Wedding Dress
138 - The Vacationers
139 - The Third Wave: An Entrepreneurâs Vision of the Future
140 - The Stranger
141 - The Shadow Hero (The Shadow Hero)
142 - The Secret (The Secret #1)
143 - The Regional Office Is Under Attack!
144 - The Psychopath Test: A Journey Through the Madness Industry
145 - The Project
146 - The Power of Now: A Guide to Spiritual Enlightenment
147 - The Omnivore's Dilemma: A Natural History of Four Meals
148 - The Nerdy Nummies Cookbook: Sweet Treats for the Geek in All of Us
149 - The Murder of Roger Ackroyd (Hercule Poirot #4)
150 - The Mistake (Off-Campus #2)
151 - The Matchmaker's Playbook (Wingmen Inc. #1)
152 - The Love and Lemons Cookbook: An Apple-to-Zucchini Celebration of Impromptu Cooking
153 - The Long Shadow of Small Ghosts: Murder and Memory in an American City
154 - The Kite Runner
155 - The House by the Lake
156 - The Glittering Court (The Glittering Court #1)
157 - The Girl on the Train
158 - The Genius of Birds
159 - The Emerald Mystery
160 - The Cookies & Cups Cookbook: 125+ sweet & savory recipes reminding you to Always Eat Dessert First
161 - The Bridge to Consciousness: I'm Writing the Bridge Between Science and Our Old and New Beliefs.
162 - The Artist's Way: A Spiritual Path to Higher Creativity
163 - The Art of War
164 - The Argonauts
165 - The 10% Entrepreneur: Live Your Startup Dream Without Quitting Your Day Job
166 - Suddenly in Love (Lake Haven #1)
167 - Something More Than This
168 - Soft Apocalypse
169 - So You've Been Publicly Shamed
170 - Shoe Dog: A Memoir by the Creator of NIKE
171 - Shobu Samurai, Project Aryoku (#3)
172 - Secrets and Lace (Fatal Hearts #1)
173 - Scarlett Epstein Hates It Here
174 - Romero and Juliet: A Tragic Tale of Love and Zombies
175 - Redeeming Love
176 - Poses for Artists Volume 1 - Dynamic and Sitting Poses: An Essential Reference for Figure Drawing and the Human Form
177 - Poems That Make Grown Women Cry
178 - Nightingale, Sing
179 - Night Sky with Exit Wounds
180 - Mrs. Houdini
181 - Modern Romance
182 - Miss Peregrineâs Home for Peculiar Children (Miss Peregrineâs Peculiar Children #1)
183 - Louisa: The Extraordinary Life of Mrs. Adams
184 - Little Red
185 - Library of Souls (Miss Peregrineâs Peculiar Children #3)
186 - Large Print Heart of the Pride
187 - I Had a Nice Time And Other Lies...: How to find love & sh*t like that
188 - Hollow City (Miss Peregrineâs Peculiar Children #2)
189 - Grumbles
190 - Full Moon over Noahâs Ark: An Odyssey to Mount Ararat and Beyond
191 - Frostbite (Vampire Academy #2)
192 - Follow You Home
193 - First Steps for New Christians (Print Edition)
194 - Finders Keepers (Bill Hodges Trilogy #2)
195 - Fables, Vol. 1: Legends in Exile (Fables #1)
196 - Eureka Trivia 6.0
197 - Drive: The Surprising Truth About What Motivates Us
198 - Done Rubbed Out (Reightman & Bailey #1)
199 - Doing It Over (Most Likely To #1)
200 - Deliciously Ella Every Day: Quick and Easy Recipes for Gluten-Free Snacks, Packed Lunches, and Simple Meals
201 - Dark Notes
202 - Daring Greatly: How the Courage to Be Vulnerable Transforms the Way We Live, Love, Parent, and Lead
203 - Close to You
204 - Chasing Heaven: What Dying Taught Me About Living
205 - Big Magic: Creative Living Beyond Fear
206 - Becoming Wise: An Inquiry into the Mystery and Art of Living
207 - Beauty Restored (Riley Family Legacy Novellas #3)
208 - Batman: The Long Halloween (Batman)
209 - Batman: The Dark Knight Returns (Batman)
210 - Ayumi's Violin
211 - Anonymous
212 - Amy Meets the Saints and Sages
213 - Amid the Chaos
214 - Amatus
215 - Agnostic: A Spirited Manifesto
216 - Zealot: The Life and Times of Jesus of Nazareth
217 - You (You #1)
218 - Wonder Woman: Earth One, Volume One (Wonder Woman: Earth One #1)
219 - Wild Swans
220 - Why the Right Went Wrong: Conservatism--From Goldwater to the Tea Party and Beyond
221 - Whole Lotta Creativity Going On: 60 Fun and Unusual Exercises to Awaken and Strengthen Your Creativity
222 - What's It Like in Space?: Stories from Astronauts Who've Been There
223 - We Are Robin, Vol. 1: The Vigilante Business (We Are Robin #1)
224 - Walt Disney's Alice in Wonderland
225 - V for Vendetta (V for Vendetta Complete)
226 - Until Friday Night (The Field Party #1)
227 - Unbroken: A World War II Story of Survival, Resilience, and Redemption
228 - Twenty Yawns
229 - Through the Woods
230 - This Is Where It Ends
231 - The Year of Magical Thinking
232 - The Wright Brothers
233 - The White Queen (The Cousins' War #1)
234 - The Wedding Pact (The O'Malleys #2)
235 - The Time Keeper
236 - The Testament of Mary
237 - The Star-Touched Queen
238 - The Songs of the Gods
239 - The Song of Achilles
240 - The Rosie Project (Don Tillman #1)
241 - The Power of Habit: Why We Do What We Do in Life and Business
242 - The Marriage of Opposites
243 - The Lucifer Effect: Understanding How Good People Turn Evil
244 - The Long Haul (Diary of a Wimpy Kid #9)
245 - The Loney
246 - The Literature Book (Big Ideas Simply Explained)
247 - The Last Mile (Amos Decker #2)
248 - The Immortal Life of Henrietta Lacks
249 - The Hidden Oracle (The Trials of Apollo #1)
250 - The Help Yourself Cookbook for Kids: 60 Easy Plant-Based Recipes Kids Can Make to Stay Healthy and Save the Earth
251 - The Guilty (Will Robie #4)
252 - The First Hostage (J.B. Collins #2)
253 - The Dovekeepers
254 - The Darkest Lie
255 - The Bane Chronicles (The Bane Chronicles #1-11)
256 - The Bad-Ass Librarians of Timbuktu: And Their Race to Save the Worldâs Most Precious Manuscripts
257 - The 14th Colony (Cotton Malone #11)
258 - That Darkness (Gardiner and Renner #1)
259 - Tastes Like Fear (DI Marnie Rome #3)
260 - Take Me with You
261 - Swell: A Year of Waves
262 - Superman Vol. 1: Before Truth (Superman by Gene Luen Yang #1)
263 - Still Life with Bread Crumbs
264 - Steve Jobs
265 - Sorting the Beef from the Bull: The Science of Food Fraud Forensics
266 - Someone Like You (The Harrisons #2)
267 - So Cute It Hurts!!, Vol. 6 (So Cute It Hurts!! #6)
268 - Shtum
269 - See America: A Celebration of Our National Parks & Treasured Sites
270 - salt.
271 - Robin War
272 - Red Hood/Arsenal, Vol. 1: Open for Business (Red Hood/Arsenal #1)
273 - Rain Fish
274 - Quarter Life Poetry: Poems for the Young, Broke and Hangry
275 - Pet Sematary
276 - Overload: How to Unplug, Unwind, and Unleash Yourself from the Pressure of Stress
277 - Once Was a Time
278 - Old School (Diary of a Wimpy Kid #10)
279 - No Dream Is Too High: Life Lessons From a Man Who Walked on the Moon
280 - Naruto (3-in-1 Edition), Vol. 14: Includes Vols. 40, 41 & 42 (Naruto: Omnibus #14)
281 - My Name Is Lucy Barton
282 - My Mrs. Brown
283 - My Kind of Crazy
284 - Mr. Mercedes (Bill Hodges Trilogy #1)
285 - More Than Music (Chasing the Dream #1)
286 - Made to Stick: Why Some Ideas Survive and Others Die
287 - Luis Paints the World
288 - Luckiest Girl Alive
289 - Lowriders to the Center of the Earth (Lowriders in Space #2)
290 - Love Is a Mix Tape (Music #1)
291 - Looking for Lovely: Collecting the Moments that Matter
292 - Living Leadership by Insight: A Good Leader Achieves, a Great Leader Builds Monuments
293 - Let It Out: A Journey Through Journaling
294 - Lady Midnight (The Dark Artifices #1)
295 - It's All Easy: Healthy, Delicious Weeknight Meals in under 30 Minutes
296 - Island of Dragons (Unwanteds #7)
297 - I Know What I'm Doing -- and Other Lies I Tell Myself: Dispatches from a Life Under Construction
298 - I Am Pilgrim (Pilgrim #1)
299 - Hyperbole and a Half: Unfortunate Situations, Flawed Coping Mechanisms, Mayhem, and Other Things That Happened
300 - Hush, Hush (Hush, Hush #1)
301 - Hold Your Breath (Search and Rescue #1)
302 - Hamilton: The Revolution
303 - Greek Mythic History
304 - God: The Most Unpleasant Character in All Fiction
305 - Glory over Everything: Beyond The Kitchen House
306 - Feathers: Displays of Brilliant Plumage
307 - Far & Away: Places on the Brink of Change: Seven Continents, Twenty-Five Years
308 - Every Last Word
309 - Eligible (The Austen Project #4)
310 - El Deafo
311 - Eight Hundred Grapes
312 - Eaternity: More than 150 Deliciously Easy Vegan Recipes for a Long, Healthy, Satisfied, Joyful Life
313 - Eat Fat, Get Thin
314 - Don't Get Caught
315 - Doctor Sleep (The Shining #2)
316 - Demigods & Magicians: Percy and Annabeth Meet the Kanes (Percy Jackson & Kane Chronicles Crossover #1-3)
317 - Dear Mr. Knightley
318 - Daily Fantasy Sports
319 - Crazy Love: Overwhelmed by a Relentless God
320 - Cometh the Hour (The Clifton Chronicles #6)
321 - Code Name Verity (Code Name Verity #1)
322 - Clockwork Angel (The Infernal Devices #1)
323 - City of Glass (The Mortal Instruments #3)
324 - City of Fallen Angels (The Mortal Instruments #4)
325 - City of Bones (The Mortal Instruments #1)
326 - City of Ashes (The Mortal Instruments #2)
327 - Cell
328 - Catching Jordan (Hundred Oaks)
329 - Carry On, Warrior: Thoughts on Life Unarmed
330 - Carrie
331 - Buying In: The Secret Dialogue Between What We Buy and Who We Are
332 - Brain on Fire: My Month of Madness
333 - Batman: Europa
334 - Barefoot Contessa Back to Basics
335 - Barefoot Contessa at Home: Everyday Recipes You'll Make Over and Over Again
336 - Balloon Animals
337 - Art Ops Vol. 1
338 - Aristotle and Dante Discover the Secrets of the Universe (Aristotle and Dante Discover the Secrets of the Universe #1)
339 - Angels Walking (Angels Walking #1)
340 - Angels & Demons (Robert Langdon #1)
341 - All the Light We Cannot See
342 - Adulthood Is a Myth: A "Sarah's Scribbles" Collection
343 - Abstract City
344 - A Time of Torment (Charlie Parker #14)
345 - A Study in Scarlet (Sherlock Holmes #1)
346 - A Series of Catastrophes and Miracles: A True Story of Love, Science, and Cancer
347 - A People's History of the United States
348 - A Man Called Ove
349 - A Distant Mirror: The Calamitous 14th Century
350 - A Brush of Wings (Angels Walking #3)
351 - 1491: New Revelations of the Americas Before Columbus
352 - The Three Searches, Meaning, and the Story
353 - Searching for Meaning in Gailana
354 - Rook
355 - My Kitchen Year: 136 Recipes That Saved My Life
356 - 13 Hours: The Inside Account of What Really Happened In Benghazi
357 - Will You Won't You Want Me?
358 - Tipping Point for Planet Earth: How Close Are We to the Edge?
359 - The Star-Touched Queen
360 - The Silent Sister (Riley MacPherson #1)
361 - The Midnight Watch: A Novel of the Titanic and the Californian
362 - The Lonely City: Adventures in the Art of Being Alone
363 - The Gray Rhino: How to Recognize and Act on the Obvious Dangers We Ignore
364 - The Golden Condom: And Other Essays on Love Lost and Found
365 - The Epidemic (The Program 0.6)
366 - The Dinner Party
367 - The Diary of a Young Girl
368 - The Children
369 - Stars Above (The Lunar Chronicles #4.5)
370 - Snatched: How A Drug Queen Went Undercover for the DEA and Was Kidnapped By Colombian Guerillas
371 - Raspberry Pi Electronics Projects for the Evil Genius
372 - Quench Your Own Thirst: Business Lessons Learned Over a Beer or Two
373 - Psycho: Sanitarium (Psycho #1.5)
374 - Poisonous (Max Revere Novels #3)
375 - One with You (Crossfire #5)
376 - No Love Allowed (Dodge Cove #1)
377 - Murder at the 42nd Street Library (Raymond Ambler #1)
378 - Most Wanted
379 - Love, Lies and Spies
380 - How to Speak Golf: An Illustrated Guide to Links Lingo
381 - Hide Away (Eve Duncan #20)
382 - Furiously Happy: A Funny Book About Horrible Things
383 - Everyday Italian: 125 Simple and Delicious Recipes
384 - Equal Is Unfair: America's Misguided Fight Against Income Inequality
385 - Eleanor & Park
386 - Dirty (Dive Bar #1)
387 - Can You Keep a Secret? (Fear Street Relaunch #4)
388 - Boar Island (Anna Pigeon #19)
389 - A Paris Apartment
390 - A la Mode: 120 Recipes in 60 Pairings: Pies, Tarts, Cakes, Crisps, and More Topped with Ice Cream, Gelato, Frozen Custard, and More
391 - Troublemaker: Surviving Hollywood and Scientology
392 - The Widow
393 - The Sleep Revolution: Transforming Your Life, One Night at a Time
394 - The Improbability of Love
395 - The Art of Startup Fundraising
396 - Take Me Home Tonight (Rock Star Romance #3)
397 - Sleeping Giants (Themis Files #1)
398 - Setting the World on Fire: The Brief, Astonishing Life of St. Catherine of Siena
399 - Playing with Fire
400 - Off the Hook (Fishing for Trouble #1)
401 - Mothering Sunday
402 - Mother, Can You Not?
403 - M Train
404 - Lilac Girls
405 - Lies and Other Acts of Love
406 - Lab Girl
407 - Keep Me Posted
408 - It Didn't Start with You: How Inherited Family Trauma Shapes Who We Are and How to End the Cycle
409 - Grey (Fifty Shades #4)
410 - Exit, Pursued by a Bear
411 - Daredevils
412 - Cravings: Recipes for What You Want to Eat
413 - Born for This: How to Find the Work You Were Meant to Do
414 - Arena
415 - Adultery

In [ ]:
df = pd.DataFrame(
    books_data,
    columns=["id", "title", "category", "description"]
)

In [ ]:
print("Done!")
print(f"Saved {len(books_data)} books in books_data.json")

Done!
Saved 1000 books in books_data.json

In [ ]:
df.to_csv("books_data.csv", index=False, encoding="utf-8-sig")

In [ ]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# Setup NLTK
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
import string

def clean_description(text):
    if pd.isna(text):
        return ""

    text = str(text).lower()

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Remove non-alphabetic characters
    text = re.sub(r'[^a-z\s]', '', text)

    tokens = word_tokenize(text)

    stop_words = set(stopwords.words('english'))
    tokens = [w for w in tokens if w not in stop_words]

    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(w) for w in tokens]

    return " ".join(tokens)

df['cleaned_description'] = df['description'].apply(clean_description)

In [ ]:
print(df[['description', 'cleaned_description']].head())

                                         description  \
0  It's hard to imagine a world without A Light i...
1  "Erotic and absorbing...Written with starling ...
2  Dans une France assez proche de la nÃ´tre, un ...
3  WICKED above her hipbone, GIRL across her hear...
4  From a renowned historian comes a groundbreaki...

                                 cleaned_description
0  hard imagine world without light attic nowclas...
1  erotic absorbingwritten starling powerthe new ...
2  dans une france assez proche de la ntre un hom...
3  wicked hipbone girl across heart word like roa...
4  renowned historian come groundbreaking narrati...

In [ ]:
df.head()

,id,title,category,description,cleaned_description
0,1,A Light in the Attic,Poetry,It's hard to imagine a world without A Light i...,hard imagine world without light attic nowclas...
1,2,Tipping the Velvet,Historical Fiction,"""Erotic and absorbing...Written with starling ...",erotic absorbingwritten starling powerthe new ...
2,3,Soumission,Fiction,"Dans une France assez proche de la nÃ´tre, un ...",dans une france assez proche de la ntre un hom...
3,4,Sharp Objects,Mystery,"WICKED above her hipbone, GIRL across her hear...",wicked hipbone girl across heart word like roa...
4,5,Sapiens: A Brief History of Humankind,History,From a renowned historian comes a groundbreaki...,renowned historian come groundbreaking narrati...

In [ ]:
df = df.drop(columns=['description'])
df.head()

,id,title,category,cleaned_description
0,1,A Light in the Attic,Poetry,hard imagine world without light attic nowclas...
1,2,Tipping the Velvet,Historical Fiction,erotic absorbingwritten starling powerthe new ...
2,3,Soumission,Fiction,dans une france assez proche de la ntre un hom...
3,4,Sharp Objects,Mystery,wicked hipbone girl across heart word like roa...
4,5,Sapiens: A Brief History of Humankind,History,renowned historian come groundbreaking narrati...

In [ ]:

from sklearn.feature_extraction.text import CountVectorizer

# Initialize CountVectorizer to extract words
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df['cleaned_description'])

# Get the vocabulary (terms)
vocabulary = vectorizer.get_feature_names_out()
print(f"Total unique words in vocabulary: {len(vocabulary)}")

Total unique words in vocabulary: 19837

In [ ]:

# Calculate word frequencies
word_counts = X.toarray().sum(axis=0)
words_freq = pd.DataFrame({'term': vocabulary, 'occurrence': word_counts})
words_freq = words_freq.sort_values(by='occurrence', ascending=False)

# Display the top 20 most common terms
print("Top 20 most frequent terms:")
display(words_freq.head(20))

Top 20 most frequent terms:

         term  occurrence
10259    life         946
11950     new         935
12363     one         900
17811    time         669
19565   world         639
1996     book         616
10572    love         539
19706    year         534
16865   story         521
6589     find         399
6326   family         385
6625    first         382
19168     way         375
1193   author         331
10332    like         323
10788    make         319
9880     know         297
12974  people         297
19745    york         287
18307     two         286

## **3-Inverted Index Construction**

In this step, we build an **inverted index** based on the preprocessed text data stored in the `cleaned_description` column.

The goal is to transform the collection of documents into a structured index that maps each term to the documents in which it appears, along with additional statistical information.

In [ ]:
#1: Tokenization from cleaned_description

docs_tokens = []

for text in df['cleaned_description']:
    if pd.isna(text):
        tokens = []
    else:
        tokens = text.split()
    docs_tokens.append(tokens)


# 2: Extract unique terms (vocabulary)

all_terms = []
for tokens in docs_tokens:
    all_terms.extend(tokens)

# remove frequent words to get vocabulary
terms = list(set(all_terms))

print("Number of unique terms:", len(terms))

Number of unique terms: 19856

In [ ]:
#3: Build the Inverted Index

inverted_index = {}

for term in terms:
    term_info = {}

    for i, tokens in enumerate(docs_tokens):
        if term in tokens:
            # Calculate term frequency (TF) in each document
            freq = tokens.count(term)

            term_info[f"Document {i+1}"] = {
                "tf": freq
            }

    # Store document frequency (df) and postings list
    inverted_index[term] = {
        "df": len(term_info),        # number of documents containing the term
        "postings": term_info        # term frequency per document
    }



# 4: Display a sample of the inverted index

for term, data in list(inverted_index.items())[:10]:
    print(term, "->", data)

reflect -> {'df': 8, 'postings': {'Document 91': {'tf': 1}, 'Document 221': {'tf': 1}, 'Document 279': {'tf': 1}, 'Document 437': {'tf': 1}, 'Document 552': {'tf': 1}, 'Document 556': {'tf': 1}, 'Document 822': {'tf': 1}, 'Document 892': {'tf': 1}}}
authoritativelike -> {'df': 1, 'postings': {'Document 299': {'tf': 2}}}
mri -> {'df': 1, 'postings': {'Document 587': {'tf': 1}}}
abusive -> {'df': 2, 'postings': {'Document 730': {'tf': 1}, 'Document 989': {'tf': 2}}}
gangsteron -> {'df': 1, 'postings': {'Document 178': {'tf': 2}}}
salad -> {'df': 14, 'postings': {'Document 58': {'tf': 2}, 'Document 91': {'tf': 1}, 'Document 122': {'tf': 1}, 'Document 200': {'tf': 2}, 'Document 295': {'tf': 2}, 'Document 312': {'tf': 2}, 'Document 335': {'tf': 1}, 'Document 380': {'tf': 1}, 'Document 522': {'tf': 1}, 'Document 530': {'tf': 1}, 'Document 552': {'tf': 1}, 'Document 561': {'tf': 2}, 'Document 591': {'tf': 4}, 'Document 720': {'tf': 1}}}
sexy -> {'df': 18, 'postings': {'Document 76': {'tf': 1}, 'Document 114': {'tf': 2}, 'Document 127': {'tf': 1}, 'Document 150': {'tf': 2}, 'Document 166': {'tf': 2}, 'Document 266': {'tf': 2}, 'Document 389': {'tf': 1}, 'Document 396': {'tf': 1}, 'Document 420': {'tf': 1}, 'Document 621': {'tf': 1}, 'Document 649': {'tf': 2}, 'Document 812': {'tf': 1}, 'Document 893': {'tf': 1}, 'Document 933': {'tf': 1}, 'Document 951': {'tf': 3}, 'Document 953': {'tf': 2}, 'Document 972': {'tf': 2}, 'Document 976': {'tf': 2}}}
paleo -> {'df': 1, 'postings': {'Document 309': {'tf': 1}}}
thatto -> {'df': 1, 'postings': {'Document 487': {'tf': 1}}}
mourning -> {'df': 3, 'postings': {'Document 507': {'tf': 2}, 'Document 532': {'tf': 1}, 'Document 841': {'tf': 2}}}



> The inverted index maps each term to the documents it appears in, along with term frequency and document frequency, enabling efficient search and ranking.

In [ ]:
positional_index = {}

for i, tokens in enumerate(docs_tokens):
    for pos, term in enumerate(tokens):
        if term not in positional_index:
            positional_index[term] = {}

        if f"Document {i+1}" not in positional_index[term]:
            positional_index[term][f"Document {i+1}"] = []

        positional_index[term][f"Document {i+1}"].append(pos)

In [ ]:
for term, data in list(positional_index.items())[:3]:
    print(f"Term: {term}")

    for doc, positions in data.items():
        print(f"   {doc} → positions: {positions}")

    print("-" * 50)

Term: hard
   Document 1 → positions: [0, 37]
   Document 77 → positions: [22]
   Document 123 → positions: [88]
   Document 133 → positions: [7, 44]
   Document 168 → positions: [125]
   Document 186 → positions: [86]
   Document 245 → positions: [100]
   Document 267 → positions: [24, 53]
   Document 288 → positions: [32, 70]
   Document 300 → positions: [17, 54]
   Document 301 → positions: [12, 50]
   Document 325 → positions: [29, 65]
   Document 329 → positions: [82]
   Document 391 → positions: [133]
   Document 395 → positions: [208, 628]
   Document 411 → positions: [98]
   Document 442 → positions: [218]
   Document 473 → positions: [292]
   Document 592 → positions: [13, 50]
   Document 597 → positions: [79]
   Document 602 → positions: [85]
   Document 613 → positions: [138]
   Document 617 → positions: [87]
   Document 638 → positions: [175]
   Document 645 → positions: [147]
   Document 726 → positions: [114]
   Document 730 → positions: [6, 47]
   Document 732 → positions: [166]
   Document 799 → positions: [101]
   Document 875 → positions: [63]
   Document 888 → positions: [101]
   Document 905 → positions: [91]
   Document 906 → positions: [21, 63]
   Document 948 → positions: [82]
   Document 976 → positions: [112]
   Document 983 → positions: [34, 76]
   Document 986 → positions: [91]
--------------------------------------------------
Term: imagine
   Document 1 → positions: [1, 38]
   Document 128 → positions: [19, 50]
   Document 153 → positions: [145]
   Document 258 → positions: [81]
   Document 353 → positions: [147]
   Document 355 → positions: [108]
   Document 357 → positions: [83]
   Document 550 → positions: [126]
   Document 615 → positions: [10, 47]
   Document 635 → positions: [106]
   Document 745 → positions: [18, 48, 62]
   Document 748 → positions: [28, 65]
--------------------------------------------------
Term: world
   Document 1 → positions: [2, 39]
   Document 5 → positions: [149]
   Document 6 → positions: [83]
   Document 9 → positions: [11, 47, 175]
   Document 10 → positions: [81]
   Document 17 → positions: [24, 62]
   Document 20 → positions: [105]
   Document 24 → positions: [72]
   Document 26 → positions: [13, 52]
   Document 28 → positions: [86]
   Document 29 → positions: [106, 137]
   Document 30 → positions: [13, 54]
   Document 34 → positions: [74]
   Document 35 → positions: [10, 14, 42, 46, 64]
   Document 40 → positions: [147, 153]
   Document 41 → positions: [93]
   Document 42 → positions: [64]
   Document 44 → positions: [5, 40]
   Document 49 → positions: [67, 113, 155]
   Document 52 → positions: [1, 11, 33, 43]
   Document 56 → positions: [11, 44, 219]
   Document 66 → positions: [19, 56]
   Document 72 → positions: [126]
   Document 78 → positions: [25]
   Document 80 → positions: [2]
   Document 82 → positions: [6]
   Document 91 → positions: [92, 190]
   Document 99 → positions: [24, 60]
   Document 101 → positions: [139]
   Document 102 → positions: [85]
   Document 108 → positions: [78]
   Document 113 → positions: [122]
   Document 116 → positions: [142]
   Document 117 → positions: [85]
   Document 122 → positions: [2, 10, 40, 48, 132, 144]
   Document 126 → positions: [99]
   Document 127 → positions: [98]
   Document 128 → positions: [152]
   Document 136 → positions: [96]
   Document 139 → positions: [24, 59, 116, 207]
   Document 142 → positions: [65]
   Document 143 → positions: [0, 34, 111]
   Document 144 → positions: [25, 59, 68]
   Document 145 → positions: [13, 28, 48, 63]
   Document 146 → positions: [85]
   Document 147 → positions: [192, 207, 308]
   Document 154 → positions: [102]
   Document 155 → positions: [6, 21, 44, 59]
   Document 156 → positions: [28, 64, 86]
   Document 158 → positions: [87, 250]
   Document 163 → positions: [70]
   Document 166 → positions: [125]
   Document 168 → positions: [19, 56, 100]
   Document 169 → positions: [6, 45]
   Document 170 → positions: [21, 57, 112, 135]
   Document 171 → positions: [22, 59]
   Document 172 → positions: [25, 60]
   Document 173 → positions: [82]
   Document 174 → positions: [84]
   Document 177 → positions: [129]
   Document 181 → positions: [232, 275]
   Document 183 → positions: [148]
   Document 188 → positions: [88]
   Document 190 → positions: [21, 59, 175]
   Document 197 → positions: [29, 65]
   Document 203 → positions: [144]
   Document 205 → positions: [129]
   Document 206 → positions: [252, 268]
   Document 209 → positions: [8, 49, 148]
   Document 215 → positions: [111]
   Document 224 → positions: [99]
   Document 225 → positions: [13, 47]
   Document 227 → positions: [68]
   Document 232 → positions: [12, 31, 48, 67]
   Document 235 → positions: [10, 47, 88, 113]
   Document 237 → positions: [25, 57]
   Document 242 → positions: [150]
   Document 246 → positions: [19, 53, 111]
   Document 249 → positions: [29, 67]
   Document 250 → positions: [158]
   Document 251 → positions: [9, 41]
   Document 252 → positions: [22, 60, 89, 116]
   Document 256 → positions: [95]
   Document 258 → positions: [92]
   Document 261 → positions: [3, 42]
   Document 265 → positions: [163]
   Document 266 → positions: [110]
   Document 269 → positions: [21, 54]
   Document 273 → positions: [137]
   Document 277 → positions: [12, 43, 70]
   Document 280 → positions: [15, 54]
   Document 282 → positions: [205]
   Document 286 → positions: [7, 43]
   Document 287 → positions: [22, 38, 64, 80]
   Document 294 → positions: [3, 35, 152]
   Document 296 → positions: [83]
   Document 304 → positions: [110]
   Document 319 → positions: [79]
   Document 325 → positions: [108]
   Document 326 → positions: [34, 73, 86]
   Document 329 → positions: [103]
   Document 331 → positions: [360, 393, 425]
   Document 337 → positions: [101]
   Document 338 → positions: [23, 57]
   Document 341 → positions: [30, 70]
   Document 348 → positions: [6, 46]
   Document 349 → positions: [69]
   Document 351 → positions: [99, 110]
   Document 352 → positions: [79]
   Document 353 → positions: [3, 38, 167]
   Document 355 → positions: [6, 41, 203]
   Document 359 → positions: [25, 57]
   Document 363 → positions: [73, 102]
   Document 365 → positions: [21, 56]
   Document 367 → positions: [12, 48, 87]
   Document 368 → positions: [117]
   Document 369 → positions: [96]
   Document 370 → positions: [17, 54]
   Document 380 → positions: [33, 69]
   Document 393 → positions: [187, 213]
   Document 394 → positions: [8, 36, 46, 74]
   Document 395 → positions: [38, 78, 87, 112, 382, 562, 610, 631]
   Document 397 → positions: [5, 44]
   Document 398 → positions: [149]
   Document 403 → positions: [69, 70]
   Document 404 → positions: [3, 29, 40, 67]
   Document 405 → positions: [103]
   Document 409 → positions: [1, 31, 37, 67]
   Document 414 → positions: [7, 33, 45, 72, 121]
   Document 419 → positions: [28, 62]
   Document 425 → positions: [84, 86, 97]
   Document 429 → positions: [3, 40, 140]
   Document 436 → positions: [61, 78, 81]
   Document 437 → positions: [79]
   Document 441 → positions: [129]
   Document 442 → positions: [133, 142]
   Document 446 → positions: [112]
   Document 449 → positions: [20, 59]
   Document 451 → positions: [99]
   Document 458 → positions: [6]
   Document 465 → positions: [139]
   Document 466 → positions: [89]
   Document 475 → positions: [26, 60]
   Document 476 → positions: [129]
   Document 478 → positions: [102]
   Document 480 → positions: [87]
   Document 481 → positions: [166]
   Document 484 → positions: [1, 37]
   Document 485 → positions: [14, 32, 53, 71]
   Document 486 → positions: [207]
   Document 487 → positions: [127]
   Document 488 → positions: [1, 33, 100, 117, 151]
   Document 491 → positions: [86]
   Document 495 → positions: [21, 61]
   Document 496 → positions: [14, 49]
   Document 497 → positions: [14, 49]
   Document 499 → positions: [16, 50, 200]
   Document 504 → positions: [112]
   Document 506 → positions: [23, 54]
   Document 507 → positions: [6, 46]
   Document 508 → positions: [7, 30, 40, 63]
   Document 515 → positions: [99]
   Document 517 → positions: [29, 63]
   Document 521 → positions: [24, 57]
   Document 524 → positions: [21, 54]
   Document 528 → positions: [86]
   Document 532 → positions: [17, 53]
   Document 534 → positions: [122]
   Document 542 → positions: [90]
   Document 544 → positions: [59]
   Document 546 → positions: [24, 60, 238]
   Document 548 → positions: [29, 64, 73]
   Document 550 → positions: [19, 55, 123]
   Document 552 → positions: [283]
   Document 553 → positions: [85]
   Document 554 → positions: [79]
   Document 556 → positions: [111]
   Document 557 → positions: [2, 33]
   Document 560 → positions: [126]
   Document 562 → positions: [104]
   Document 565 → positions: [28, 59, 115]
   Document 567 → positions: [100]
   Document 575 → positions: [100]
   Document 576 → positions: [32, 71]
   Document 581 → positions: [11, 14, 46, 49, 94]
   Document 582 → positions: [14, 47]
   Document 583 → positions: [125]
   Document 585 → positions: [18, 56]
   Document 586 → positions: [27, 66, 125]
   Document 590 → positions: [138]
   Document 593 → positions: [5, 34, 44, 73, 136]
   Document 594 → positions: [139]
   Document 596 → positions: [6, 38]
   Document 607 → positions: [113]
   Document 610 → positions: [101]
   Document 631 → positions: [19, 56, 141]
   Document 633 → positions: [32, 71, 141]
   Document 634 → positions: [33]
   Document 636 → positions: [107]
   Document 640 → positions: [23, 63, 158, 272, 371]
   Document 646 → positions: [6, 42]
   Document 656 → positions: [0, 36, 111]
   Document 657 → positions: [23, 60]
   Document 658 → positions: [34, 73, 99]
   Document 660 → positions: [65]
   Document 662 → positions: [10, 30, 47, 67, 83]
   Document 664 → positions: [81, 90, 179]
   Document 671 → positions: [3, 38]
   Document 672 → positions: [93]
   Document 675 → positions: [88]
   Document 677 → positions: [103]
   Document 682 → positions: [101, 103]
   Document 685 → positions: [23, 55]
   Document 686 → positions: [79]
   Document 687 → positions: [6, 18, 32, 44]
   Document 689 → positions: [84]
   Document 690 → positions: [75, 123]
   Document 691 → positions: [18, 52]
   Document 695 → positions: [24, 58, 84]
   Document 697 → positions: [113]
   Document 704 → positions: [269]
   Document 707 → positions: [22, 60]
   Document 710 → positions: [21, 56, 157]
   Document 711 → positions: [115, 146]
   Document 717 → positions: [86, 130]
   Document 718 → positions: [77]
   Document 719 → positions: [1, 19, 21, 27, 34, 52, 54, 60, 67, 110]
   Document 722 → positions: [33, 70]
   Document 727 → positions: [11, 44, 147]
   Document 728 → positions: [26, 59]
   Document 731 → positions: [105]
   Document 737 → positions: [95, 119, 174, 238]
   Document 740 → positions: [6, 30, 38, 61, 129]
   Document 742 → positions: [6, 7, 42, 43]
   Document 743 → positions: [18, 55]
   Document 747 → positions: [4, 35]
   Document 748 → positions: [18, 55, 91, 96]
   Document 750 → positions: [32, 67]
   Document 751 → positions: [73]
   Document 755 → positions: [11, 31, 45, 65]
   Document 756 → positions: [15, 49]
   Document 758 → positions: [77]
   Document 762 → positions: [95]
   Document 768 → positions: [16, 54]
   Document 780 → positions: [66]
   Document 782 → positions: [85, 112]
   Document 783 → positions: [22, 56]
   Document 792 → positions: [24, 62, 100]
   Document 796 → positions: [14, 53]
   Document 797 → positions: [9, 38]
   Document 799 → positions: [86]
   Document 802 → positions: [17, 48]
   Document 804 → positions: [5, 40]
   Document 805 → positions: [110]
   Document 806 → positions: [112]
   Document 807 → positions: [95]
   Document 817 → positions: [75]
   Document 818 → positions: [119, 141]
   Document 820 → positions: [12, 51]
   Document 825 → positions: [36, 74, 111]
   Document 826 → positions: [82, 186]
   Document 828 → positions: [3, 36]
   Document 829 → positions: [136]
   Document 831 → positions: [25, 64, 150]
   Document 835 → positions: [18, 55, 107]
   Document 838 → positions: [20, 51]
   Document 840 → positions: [86, 97]
   Document 845 → positions: [77]
   Document 848 → positions: [4, 43, 81]
   Document 850 → positions: [110]
   Document 852 → positions: [0, 37]
   Document 853 → positions: [11, 53, 133, 211, 218]
   Document 855 → positions: [12, 45, 69, 79]
   Document 856 → positions: [86]
   Document 858 → positions: [114]
   Document 861 → positions: [74]
   Document 862 → positions: [101]
   Document 864 → positions: [97]
   Document 865 → positions: [90]
   Document 866 → positions: [21, 53]
   Document 867 → positions: [132]
   Document 868 → positions: [27, 62]
   Document 869 → positions: [8, 15, 41, 48]
   Document 872 → positions: [75]
   Document 885 → positions: [118]
   Document 886 → positions: [165, 193]
   Document 889 → positions: [75]
   Document 891 → positions: [72]
   Document 893 → positions: [30, 68]
   Document 897 → positions: [9]
   Document 901 → positions: [17, 53]
   Document 904 → positions: [6, 48]
   Document 905 → positions: [29, 61]
   Document 910 → positions: [88]
   Document 914 → positions: [86]
   Document 915 → positions: [22, 62]
   Document 918 → positions: [76]
   Document 920 → positions: [76]
   Document 927 → positions: [11, 47]
   Document 930 → positions: [114]
   Document 931 → positions: [14, 47, 86, 118]
   Document 943 → positions: [37, 76]
   Document 948 → positions: [70]
   Document 952 → positions: [1, 34]
   Document 953 → positions: [32, 73]
   Document 955 → positions: [87]
   Document 959 → positions: [15, 38, 54, 77]
   Document 960 → positions: [165, 199]
   Document 962 → positions: [8, 41]
   Document 963 → positions: [121]
   Document 964 → positions: [8, 17, 41, 50]
   Document 969 → positions: [28, 62]
   Document 971 → positions: [36, 76]
   Document 977 → positions: [35, 72]
   Document 978 → positions: [36, 77]
   Document 980 → positions: [27]
   Document 982 → positions: [10, 46]
   Document 991 → positions: [134]
   Document 993 → positions: [96, 131]
   Document 995 → positions: [72]
   Document 1000 → positions: [1, 5, 39, 43]
--------------------------------------------------

# 4.Search Engine Module

This section implements the search functionality using the constructed positional inverted index.

### Implemented Features:
- Single term search
- Multi-term AND search
- Phrase search
- Result display

##  Single Term Search

- Search for one term  
- Return documents + positions

In [ ]:
def search_term(term, positional_index):
    # Convert term to lowercase
    term = term.lower()

    # Check if term exists in the index
    if term in positional_index:
        results = positional_index[term]

        print(f"Term '{term}' found in:")

        # Iterate over documents and positions
        for doc, positions in results.items():
            print(f"{doc} -> positions: {positions}")
    else:
        print(f"Term '{term}' not found.")

In [ ]:
search_term("love", positional_index)

Term 'love' found in:
Document 1 -> positions: [35, 72]
Document 8 -> positions: [8, 41, 242]
Document 13 -> positions: [68]
Document 20 -> positions: [104]
Document 25 -> positions: [86, 117]
Document 31 -> positions: [32, 70]
Document 32 -> positions: [3, 18, 23, 33, 48, 53, 72, 85, 90, 95]
Document 39 -> positions: [77]
Document 41 -> positions: [25, 62]
Document 42 -> positions: [95]
Document 44 -> positions: [15, 50]
Document 46 -> positions: [37, 77]
Document 47 -> positions: [106]
Document 49 -> positions: [153]
Document 50 -> positions: [103]
Document 58 -> positions: [9, 44, 171]
Document 60 -> positions: [6, 46]
Document 61 -> positions: [84]
Document 73 -> positions: [115]
Document 76 -> positions: [7, 42, 131, 149]
Document 81 -> positions: [89]
Document 85 -> positions: [3, 36]
Document 100 -> positions: [90]
Document 104 -> positions: [29, 63]
Document 107 -> positions: [29, 63, 134, 157]
Document 122 -> positions: [14, 52]
Document 123 -> positions: [95]
Document 125 -> positions: [98, 139]
Document 128 -> positions: [27, 58, 185]
Document 129 -> positions: [0, 2, 28, 33, 35, 61, 83]
Document 131 -> positions: [94, 238]
Document 137 -> positions: [112, 148]
Document 148 -> positions: [112]
Document 152 -> positions: [43, 59, 78, 126]
Document 154 -> positions: [140, 146]
Document 162 -> positions: [6, 42]
Document 164 -> positions: [5, 24, 36, 55, 70]
Document 165 -> positions: [17, 45]
Document 166 -> positions: [142]
Document 167 -> positions: [5, 45]
Document 171 -> positions: [80]
Document 174 -> positions: [86, 89]
Document 175 -> positions: [83, 113, 123]
Document 177 -> positions: [88]
Document 180 -> positions: [12, 52, 144]
Document 181 -> positions: [24, 59, 140]
Document 183 -> positions: [84]
Document 187 -> positions: [139]
Document 191 -> positions: [0, 38]
Document 192 -> positions: [95]
Document 199 -> positions: [123]
Document 203 -> positions: [24, 60, 193]
Document 204 -> positions: [124]
Document 205 -> positions: [77]
Document 206 -> positions: [195]
Document 211 -> positions: [87]
Document 212 -> positions: [5, 40, 107]
Document 213 -> positions: [87]
Document 237 -> positions: [129]
Document 238 -> positions: [26, 60, 70]
Document 239 -> positions: [90]
Document 240 -> positions: [147, 162]
Document 242 -> positions: [10, 47, 130]
Document 249 -> positions: [81]
Document 250 -> positions: [32, 70]
Document 253 -> positions: [145]
Document 263 -> positions: [1, 43, 118]
Document 270 -> positions: [18]
Document 281 -> positions: [109]
Document 290 -> positions: [22, 63, 141, 146]
Document 294 -> positions: [143]
Document 319 -> positions: [17, 49, 87, 99, 102, 108, 114]
Document 320 -> positions: [23, 29, 57, 63]
Document 324 -> positions: [21, 55, 121]
Document 326 -> positions: [161]
Document 327 -> positions: [29, 66]
Document 329 -> positions: [6, 40, 86, 101]
Document 331 -> positions: [477]
Document 335 -> positions: [25, 59, 72, 206]
Document 336 -> positions: [110]
Document 339 -> positions: [17, 34, 57, 74, 120]
Document 343 -> positions: [156]
Document 345 -> positions: [68]
Document 350 -> positions: [93, 154]
Document 353 -> positions: [90]
Document 359 -> positions: [128]
Document 364 -> positions: [108, 112, 132]
Document 365 -> positions: [97]
Document 372 -> positions: [191]
Document 375 -> positions: [3, 20, 38, 55, 102, 121]
Document 376 -> positions: [4, 43, 84, 105]
Document 385 -> positions: [26, 63, 91]
Document 386 -> positions: [29, 66]
Document 394 -> positions: [12, 50, 94, 113]
Document 400 -> positions: [4, 42]
Document 401 -> positions: [91, 114]
Document 402 -> positions: [19, 54]
Document 404 -> positions: [11, 26, 48, 64]
Document 405 -> positions: [92, 120]
Document 406 -> positions: [31, 69]
Document 409 -> positions: [20, 56]
Document 410 -> positions: [0, 35, 116]
Document 412 -> positions: [106]
Document 413 -> positions: [14, 51]
Document 421 -> positions: [111, 116]
Document 432 -> positions: [17, 48, 68]
Document 433 -> positions: [28, 60, 87]
Document 434 -> positions: [85]
Document 438 -> positions: [21]
Document 439 -> positions: [29, 62]
Document 443 -> positions: [185, 193]
Document 447 -> positions: [11, 45]
Document 454 -> positions: [113]
Document 457 -> positions: [4, 41]
Document 459 -> positions: [95]
Document 465 -> positions: [113, 161]
Document 466 -> positions: [75, 110]
Document 467 -> positions: [81]
Document 474 -> positions: [112]
Document 476 -> positions: [4, 27, 44, 67]
Document 481 -> positions: [153]
Document 484 -> positions: [151]
Document 487 -> positions: [90]
Document 492 -> positions: [172]
Document 493 -> positions: [81, 83]
Document 496 -> positions: [92]
Document 499 -> positions: [70]
Document 503 -> positions: [23, 62]
Document 505 -> positions: [100]
Document 508 -> positions: [81]
Document 513 -> positions: [343, 688]
Document 515 -> positions: [89, 125]
Document 523 -> positions: [17, 57, 135, 179]
Document 524 -> positions: [67]
Document 529 -> positions: [87, 354]
Document 530 -> positions: [207]
Document 532 -> positions: [18, 54]
Document 534 -> positions: [91, 94, 108]
Document 538 -> positions: [1, 39, 86]
Document 539 -> positions: [88]
Document 540 -> positions: [123]
Document 542 -> positions: [78]
Document 543 -> positions: [125]
Document 546 -> positions: [200, 202, 234]
Document 551 -> positions: [33, 72]
Document 553 -> positions: [146]
Document 558 -> positions: [32, 70, 99, 116]
Document 560 -> positions: [35, 72]
Document 562 -> positions: [9, 50, 179]
Document 563 -> positions: [14]
Document 567 -> positions: [20, 61]
Document 577 -> positions: [186]
Document 581 -> positions: [71]
Document 586 -> positions: [92]
Document 589 -> positions: [31, 71, 82]
Document 590 -> positions: [123, 128]
Document 594 -> positions: [98, 153]
Document 595 -> positions: [74]
Document 598 -> positions: [87]
Document 605 -> positions: [116]
Document 606 -> positions: [129]
Document 607 -> positions: [3, 32, 40, 69, 75, 93, 131, 150, 163]
Document 617 -> positions: [85, 86]
Document 618 -> positions: [157]
Document 621 -> positions: [0, 37]
Document 622 -> positions: [99]
Document 623 -> positions: [77, 87]
Document 629 -> positions: [140]
Document 630 -> positions: [2, 38]
Document 634 -> positions: [9, 12, 20]
Document 636 -> positions: [23, 60]
Document 639 -> positions: [118]
Document 642 -> positions: [23, 55, 177, 225, 271, 280, 346]
Document 649 -> positions: [124]
Document 662 -> positions: [100]
Document 663 -> positions: [87]
Document 677 -> positions: [4, 41]
Document 684 -> positions: [112]
Document 685 -> positions: [14, 46]
Document 689 -> positions: [22, 60]
Document 693 -> positions: [159]
Document 694 -> positions: [8, 27, 42, 61]
Document 702 -> positions: [122]
Document 704 -> positions: [260]
Document 708 -> positions: [19, 54, 83]
Document 709 -> positions: [29, 65]
Document 711 -> positions: [102]
Document 718 -> positions: [98]
Document 720 -> positions: [13, 48]
Document 723 -> positions: [28, 59, 100]
Document 728 -> positions: [71]
Document 730 -> positions: [0, 41]
Document 732 -> positions: [11, 25, 45, 59, 95, 169, 183]
Document 734 -> positions: [0, 34, 129, 184]
Document 736 -> positions: [21, 58, 74]
Document 737 -> positions: [235]
Document 739 -> positions: [7, 9, 11, 41, 43, 45, 77, 128]
Document 749 -> positions: [112]
Document 751 -> positions: [32, 67, 69]
Document 770 -> positions: [32, 68]
Document 773 -> positions: [77, 151]
Document 776 -> positions: [78]
Document 778 -> positions: [97]
Document 790 -> positions: [74, 110, 117]
Document 795 -> positions: [169]
Document 809 -> positions: [159]
Document 810 -> positions: [22, 53]
Document 811 -> positions: [120]
Document 819 -> positions: [104]
Document 829 -> positions: [122]
Document 841 -> positions: [142]
Document 849 -> positions: [88, 124]
Document 854 -> positions: [217]
Document 858 -> positions: [172]
Document 859 -> positions: [29, 69, 102]
Document 865 -> positions: [21, 51]
Document 866 -> positions: [77, 108, 129]
Document 867 -> positions: [88, 124, 126, 129]
Document 873 -> positions: [122]
Document 874 -> positions: [2, 42]
Document 878 -> positions: [117]
Document 881 -> positions: [9, 42, 80]
Document 892 -> positions: [16, 25, 32, 49, 58, 65, 75, 80, 83, 100, 119, 136, 142, 148]
Document 893 -> positions: [31, 69]
Document 895 -> positions: [7, 43]
Document 900 -> positions: [94]
Document 902 -> positions: [94]
Document 904 -> positions: [40, 82, 111, 125]
Document 906 -> positions: [4, 46, 124]
Document 909 -> positions: [113]
Document 910 -> positions: [76]
Document 911 -> positions: [103]
Document 913 -> positions: [20, 60]
Document 921 -> positions: [129]
Document 928 -> positions: [77]
Document 933 -> positions: [138]
Document 934 -> positions: [22, 62]
Document 938 -> positions: [15, 49, 89]
Document 942 -> positions: [18, 29, 55, 66]
Document 944 -> positions: [9, 46, 109]
Document 945 -> positions: [152]
Document 949 -> positions: [126]
Document 952 -> positions: [8, 16, 41, 49]
Document 953 -> positions: [8, 49]
Document 960 -> positions: [13, 49, 99]
Document 961 -> positions: [27, 63]
Document 962 -> positions: [14, 47]
Document 969 -> positions: [18, 52]
Document 973 -> positions: [109, 120]
Document 974 -> positions: [23, 59]
Document 975 -> positions: [29, 66, 120]
Document 983 -> positions: [104, 176]
Document 984 -> positions: [1, 18, 34, 51]
Document 986 -> positions: [84]
Document 998 -> positions: [123]
Document 999 -> positions: [238]

##  Multi-Term Search (AND)

- Split query  
- Get common documents

In [ ]:
def search_multiple_terms(query, positional_index):
    # Split query into terms
    terms = query.lower().split()

    results = None

    # Find intersection of documents containing all terms
    for term in terms:
        if term in positional_index:
            docs = set(positional_index[term].keys())

            if results is None:
                results = docs
            else:
                results = results.intersection(docs)
        else:
            return []

    # Return list of matching documents
    return list(results)

In [ ]:
search_multiple_terms("love story", positional_index)

['Document 999',
 'Document 81',
 'Document 76',
 'Document 47',
 'Document 404',
 'Document 694',
 'Document 100',
 'Document 973',
 'Document 969',
 'Document 237',
 'Document 515',
 'Document 513',
 'Document 708',
 'Document 421',
 'Document 986',
 'Document 329',
 'Document 854',
 'Document 476',
 'Document 242',
 'Document 375',
 'Document 487',
 'Document 662',
 'Document 795',
 'Document 892',
 'Document 595',
 'Document 183',
 'Document 529',
 'Document 137',
 'Document 841',
 'Document 85',
 'Document 164',
 'Document 372',
 'Document 46',
 'Document 728',
 'Document 496',
 'Document 542',
 'Document 734',
 'Document 737',
 'Document 385',
 'Document 481',
 'Document 290',
 'Document 406',
 'Document 503',
 'Document 562',
 'Document 867',
 'Document 874',
 'Document 811',
 'Document 174',
 'Document 327',
 'Document 598',
 'Document 553',
 'Document 634',
 'Document 621',
 'Document 778',
 'Document 433',
 'Document 974',
 'Document 749',
 'Document 263',
 'Document 180',
 'Document 642',
 'Document 732',
 'Document 42',
 'Document 353',
 'Document 409',
 'Document 410',
 'Document 203',
 'Document 454',
 'Document 819',
 'Document 343',
 'Document 128',
 'Document 8',
 'Document 538',
 'Document 594',
 'Document 629',
 'Document 401',
 'Document 434',
 'Document 711',
 'Document 154',
 'Document 212',
 'Document 447',
 'Document 881',
 'Document 402',
 'Document 607',
 'Document 543',
 'Document 107',
 'Document 895',
 'Document 204',
 'Document 459',
 'Document 345',
 'Document 364',
 'Document 739',
 'Document 413',
 'Document 677']

##  Phrase Search

- Match exact phrase using positions  
- Terms must appear consecutively

In [ ]:
def phrase_search(query, positional_index):
    # Split query into terms
    terms = query.lower().split()

    # Check if all terms exist in the index
    if any(term not in positional_index for term in terms):
        return []

    # Get common documents containing all terms
    common_docs = set(positional_index[terms[0]].keys())

    for term in terms[1:]:
        common_docs = common_docs.intersection(positional_index[term].keys())

    result_docs = []

    # Check positions for exact phrase match
    for doc in common_docs:
        positions_lists = [positional_index[term][doc] for term in terms]

        for pos in positions_lists[0]:
            match = True

            # Check if terms appear consecutively
            for i in range(1, len(terms)):
                if (pos + i) not in positions_lists[i]:
                    match = False
                    break

            if match:
                result_docs.append(doc)
                break

    return result_docs

In [ ]:
phrase_search("love story", positional_index)

['Document 76',
 'Document 708',
 'Document 421',
 'Document 242',
 'Document 375',
 'Document 529',
 'Document 85',
 'Document 874',
 'Document 174',
 'Document 634',
 'Document 263',
 'Document 180',
 'Document 409',
 'Document 212',
 'Document 881',
 'Document 543']

# 5.K-Gram Indexing

  K-Gram Indexing is an important technique used in Information Retrieval systems to enhance search capabilities, especially in:

      Spell correction
      Fuzzy search
      Query suggestion and auto-completion

In [ ]:
def generate_kgrams(word, k=2):
    grams = []
    for i in range(len(word) - k + 1):
        grams.append(word[i:i+k])
    return grams

In [ ]:
def build_kgram_index(terms, k=2):
    kgram_index = {}

    for term in terms:
        grams = generate_kgrams(term, k)

        for gram in grams:
            if gram not in kgram_index:
                kgram_index[gram] = set()

            kgram_index[gram].add(term)

    return kgram_index


k = 2
kgram_index = build_kgram_index(terms, k)

# Jaccard Similarity

  Jaccard Similarity is used to measure the similarity between two sets. It is widely used in text processing to compare words based on their k-grams.

    Formula:
    J(A,B)=∣A∩B∣\∣A∪B∣


	​

In [ ]:
def jaccard_similarity(set1, set2):
    intersection = len(set1.intersection(set2))
    union = len(set1.union(set2))

    if union == 0:
        return 0

    return intersection / union

In [ ]:
#Find Similar Words
def find_similar_words(query, kgram_index, k=2, threshold=0.3):
    query_grams = set(generate_kgrams(query, k))

    candidates = set()

    # Collect candidate words
    for gram in query_grams:
        if gram in kgram_index:
            candidates.update(kgram_index[gram])

    results = []

    for word in candidates:
        word_grams = set(generate_kgrams(word, k))

        score = jaccard_similarity(query_grams, word_grams)

        if score >= threshold:
            results.append((word, score))

    results.sort(key=lambda x: x[1], reverse=True)

    return results

## Edit Distance

- measure of how many insertions, deletions, or substitutions are needed to convert one word into another.

In [ ]:
def edit_distance(s1, s2):
    m, n = len(s1), len(s2)

    dp = [[0]*(n+1) for _ in range(m+1)]

    for i in range(m+1):
        dp[i][0] = i
    for j in range(n+1):
        dp[0][j] = j

    for i in range(1, m+1):
        for j in range(1, n+1):
            if s1[i-1] == s2[j-1]:
                cost = 0
            else:
                cost = 1

            dp[i][j] = min(
                dp[i-1][j] + 1,      # delete
                dp[i][j-1] + 1,      # Insertion
                dp[i-1][j-1] + cost  # substitution(replace)
            )

    return dp[m][n]

- best_match with min edit distance

In [ ]:
def best_match(query, candidates):
    best_word = None
    min_dist = float('inf')

    for word, score in candidates:
        dist = edit_distance(query, word)

        if dist < min_dist:
            min_dist = dist
            best_word = word

    return best_word, min_dist

In [ ]:
print(edit_distance("retrival", "retrieval"))

1

## soundex

- algorithm that converts a word into a phonetic code so that words with similar pronunciation have the same representation.

In [ ]:
def soundex(word):
    word = word.upper()

    first_letter = word[0]
# letters with same sound map to same code
    mapping = {
        'BFPV': '1',
        'CGJKQSXZ': '2',
        'DT': '3',
        'L': '4',
        'MN': '5',
        'R': '6'
    }

    def get_code(char):
        for key in mapping:
            if char in key:
                return mapping[key]
        return '0'

    encoded = first_letter

    for char in word[1:]:
        code = get_code(char)
        if code != '0' and code != encoded[-1]:
            encoded += code

    encoded = encoded[:4].ljust(4, '0')

    return encoded

In [ ]:
def correct_query(query, kgram_index):

    candidates = find_similar_words(query, kgram_index)

    if not candidates:
        return "No suggestion found"

    best_word, min_dist = best_match(query, candidates)

    #  Soundex
    query_soundex = soundex(query)
    best_soundex = soundex(best_word)

    return {
        "query": query,
        "candidates": candidates[:5],
        "best_match": best_word,
        "edit_distance": min_dist,
        "soundex_match": query_soundex == best_soundex
    }

In [ ]:
result = correct_query("retrival", kgram_index)

print(result)

{'query': 'retrival', 'candidates': [('retrieval', 0.6666666666666666), ('rival', 0.5714285714285714), ('revival', 0.4444444444444444), ('rivalry', 0.4444444444444444), ('arrival', 0.4444444444444444)], 'best_match': 'retrieval', 'edit_distance': 1, 'soundex_match': True}